// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA070fZiil8R7CKWgS8aKYZSxJejbDZQz8',
    appId: '1:545350517317:web:14aadaf9196aa0d8dc192c',
    messagingSenderId: '545350517317',
    projectId: 'cookbook-93295',
    authDomain: 'cookbook-93295.firebaseapp.com',
    storageBucket: 'cookbook-93295.appspot.com',
    measurementId: 'G-2F3SGJV5GT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWvf3zsrfTc5Qt4Gk69f1uq2JWAgg5vIw',
    appId: '1:545350517317:android:d9e023908ab87705dc192c',
    messagingSenderId: '545350517317',
    projectId: 'cookbook-93295',
    storageBucket: 'cookbook-93295.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9iKqsNOl2lRTrq3OM8YvgR4V5mr7jjYQ',
    appId: '1:545350517317:ios:90b4f017437bb5e6dc192c',
    messagingSenderId: '545350517317',
    projectId: 'cookbook-93295',
    storageBucket: 'cookbook-93295.appspot.com',
    iosBundleId: 'com.example.cookbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9iKqsNOl2lRTrq3OM8YvgR4V5mr7jjYQ',
    appId: '1:545350517317:ios:bd1a9b8a86da4656dc192c',
    messagingSenderId: '545350517317',
    projectId: 'cookbook-93295',
    storageBucket: 'cookbook-93295.appspot.com',
    iosBundleId: 'com.example.cookbook.RunnerTests',
  );
}
